#homework
#
#java&ant

name: java&ant

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64

      - name: Build with Ant
        run:  ant -noinput -buildfile build.xml
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/jar
